kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBptbvUoUlNEPDB728KOao7bTfmImp+EyYQBXAJbKdk46eH5zww0tOA9u3TYBXXuxO7LYlwgRLP1blTCQJERUlYdWnOxLfyA8MIU0IuJgbYIY04kmMP6lMW2/KL8JxsvmXRnw/P+lCd36B1LskMtMHMv+ArpO+4PM7+IRH9yP8ZazUaAY3xBRK7QG2mQbFGb6t/lriyp4o1LVCS1cCmBIhsucqqC1VNpWAWyocu2meg0TrwLtkZX2XOCDE7+aga5TzZ+h84B8bO1y10Tom7Ln+SP/CN3NATJUIrPYq0c+ViqhBAu9eC0p45R8bWDLAFp0PRf0nup9kb+C8qz2g2xSQlX9Hxw03gygSsjzITvEOgijNVm4w591cpdeFFWzgjFh8flaAozwJBLjHsa2wLc+DiBZNVgHwKXRZkla95yL+9kS4SRVo2XQhWHiq8eYf7NY+eJsW+29cgZC0aqZNdgQ011x7uqi6pI9x4vgEaoZxONAygMiWTaETeo4gD4nrxhkWaS5qFDQ4+Nl9YzklHov3pBykW4SXLj96qqBtjqmQIprGlkIPiFsSTsrGtJ1EcYumC0cTt/gobtpdEL69YLvFT2KKMctl6Xconv0VpQeQyM4Gqhv3h6DN54jyvY2ICI7GRNzXGFD48D+xeG3MQvWkdqTfj1kGoWno6DOPwJw+C2rbjR/L9VOSKM6uq7rBoOr8n2ccpoV9TmQ==
    admin-user: AgAOEQWKsE7bR7h9/Ke8zPrkVym7KT0y8iWLNSnWocgLiSZYC2Tvw29rrTjD47Po5tyq+OM4pYi+H+5Tqp1xgBgD9NKb2qIY+YwbzwGHqlBYM+liutYdZUvEzh5JvYOll5axus6f4uKVdykOR3Ykx8Gbj9o4u/cUUKR621dHD11bwTQemE3Rpk3UD3bivrZP/lAZfJ+GKD1exZVDwnWtVYgCEzgcDQ+dcyK4tuf55bEVJLV2Jjsd71M3asp/fnoUD9sZExObPWceMu7PC9/IG16m4+ZHR3V0P97bCuyOS+tIP9lxF1pxOd8RrKo+RlI37nzq853HMNHyBpo1i8sJiL5ABrgjcOWILOxHE4aBpGY0qgoXLbzJ5w5n5B5B9+ompUg9fOSCHHdjToTAtW0Dd5tVo+sYrdx+zZofJhWqmv9qXb8WQ8HVHKIfLTdx/DEpWLIlVWhCEphmcLm7OcYevZOEdtcDPIo4PWZb7j709Es75Cz++9gxNU29bscWLn2997uUUPL6QSu72icXFTaw6stB/O94HA1qlVh47u4+SxOim9o6zda+jvPukugp0Fv8ZvFxc1gneTTU5EpmkHyJ1MwQRF/Q6yHyHnSM8K8v8iIhZiR0kFuYGJl7ULs62m0BwxmuSkw1I4FqCfOxrv352o2f8jEu/ZWS1X+PkymFPh48zssESm7aqZkZuPTfbrJQdW3iWPpXS41J
